### ISSUE TITLE
Handle inheritance

### ISSUE THREAD

**Issue by lexa62** [djberg96/win32-process#22]
I try to run this code on win32:
```
# parent.rb

require 'win32-process'
require 'socket'
socket = Socket.new(Socket::AF_INET, Socket::SOCK_STREAM, 0)
sockaddr = Socket.sockaddr_in(7777, '')
socket.bind(sockaddr)
socket.listen(5)
info = Process.create(app_name: "ruby child.rb #{socket.to_i}", inherit: true, close_handles: false)
```

```
# child.rb

require 'socket'
id = ARGV[0]
p id
p IO.new(id.to_i)
socket = Socket.for_fd(id.to_i)
client, addr = socket.accept
```

I got error:
```
child.rb:4:in `initialize': Bad file descriptor (Errno::EBADF)
        from child.rb:5:in `new'
        from child.rb:5:in `<main>'
```
Same error for file descriptors.

**Comment by djberg96** [comment]
@lexa62 I did update the function prototypes to use :int instead of :bool not long ago since BOOL is actually an integer data type. Maybe I messed something up somewhere in the conversion?

**Comment by djberg96** [comment]
@phasis68 Any ideas?

**Comment by lexa62** [comment]
This example not work on previous versions too (checked from 0.8.3 to 0.7.5).

**Comment by lexa62** [comment]
I also try to use Process.spawn:
```
spawn("ruby child.rb #{socket.to_i}", close_others: false, socket.to_i => socket.to_i)
```
But it gives an error:
```
in `spawn': wrong file descriptor (4) (ArgumentError)
```
I found this issue: https://bugs.ruby-lang.org/issues/9617
My configuration:
```
Windows 10
ruby 2.1.7p400 (2015-08-18 revision 51632) [i386-mingw32]
```

**Comment by phasis68** [comment]
Windows process inherits not file descriptors but handles.
Refer to
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724466(v=vs.85).aspx

This parent code can be modifed like this to inherit socket handle:

```
socket = Socket.new(Socket::AF_INET, Socket::SOCK_STREAM, 0)
sockaddr = Socket.sockaddr_in(7777, '')
socket.bind(sockaddr)
socket.listen(5)
handle = get_osfhandle(socket.to_i)
bool = SetHandleInformation(handle, HANDLE_FLAG_INHERIT, HANDLE_FLAG_INHERIT)
raise SystemCallError.new("SetHandleInformation", FFI.errno) unless bool
info = Process.create(app_name: "ruby child.rb #{handle}", process_inherit: true, inherit: true, close_handles: false)
```

And you can get handle and convert to file descriptor like this:

```
handle = ARGV[0]
id = open_osfhandle(handle.to_i,0)
socket = Socket.for_fd(id)
```

But, this code will fail with the message "not a socket file descriptor".
Because Ruby maintains socket descriptor list on it's own internal hash in the current Windows Ruby implementation, Ruby cannot handle inherited socket file descriptor, 

Thus, you cannot inherit socket in the current Ruby implementation on Windows platform.

**Comment by djberg96** [comment]
@phasis68 Thank you.

I think this post is also relevant: http://spin.atomicobject.com/2015/09/28/windows-sockets-ruby-extensions

In any case, closing.
